const PROJECT_ENTRY_LIST_CREATE_ENDPOINT = '/projects/';
const PROJECT_RETRIEVE_UPDATE_DESTROY_ENDPOINT = PROJECT_ENTRY_LIST_CREATE_ENDPOINT + '{project_id}/';
const PROJECT_BULK_DELETE_ENDPOINT = PROJECT_ENTRY_LIST_CREATE_ENDPOINT + 'bulk_delete/';
const LOG_ENTRY_LIST_ENDPOINT = '/projects/{project_id}/log_entries/';
const LOG_ENTRY_RETRIEVE_UPDATE_DESTROY_ENDPOINT = LOG_ENTRY_LIST_ENDPOINT + '{entry_id}/';
const PAGINATOR_QUERY_PARAM = '?page=';